import { authRoutes, discordSession, oauthStatus, AuthError } from './oauth.mjs';
import { FORMATS,initialFixtures,nextFixtures,standings,champion } from './engine.mjs';
const now=()=>new Date().toISOString();
const FORMAT_COLORS={league:'',knockout:'purple','groups + knockouts':'orange','undefined':'blue'};
class AppError extends Error{constructor(message,status=400){super(message);this.status=status}}
const fail=(s,status=400)=>{throw new AppError(s,status)};
const clean=(v,max=80)=>{if(typeof v!=='string'||!v.trim()||v.trim().length>max)fail('Campo obrigatório inválido.');return v.trim()};
const num=v=>{const n=Number(v);if(!Number.isSafeInteger(n)||n<1)fail('Identificador inválido.');return n};
const pick=(v,values)=>values.includes(v)?v:fail('Opção inválida.');
const all=async(db,sql,...args)=>(await db.prepare(sql).bind(...args).all()).results;
const one=async(db,sql,...args)=>db.prepare(sql).bind(...args).first();
const run=async(db,sql,...args)=>db.prepare(sql).bind(...args).run();
// Mamoball IDs: exactly 6 lowercase letters/digits. Later changes go through admin approval, once per 48 hours.
export const MAMO_ID=/^[a-z0-9]{6}$/;
export const ID_COOLDOWN=48*3600*1000;
export const NICK_COOLDOWN=48*3600*1000;
export const FLAG_COOLDOWN=48*3600*1000;
export const FLAG_CODE=/^[A-Z]{2}$/;
const mamoId=v=>{const s=typeof v==='string'?v.trim().toLowerCase():'';if(!MAMO_ID.test(s))fail('O ID Mamoball tem de ter 6 caracteres (letras e números, em minúsculas).');return s};
export const BANNERS=['lime','pitch','violet','ember','ocean','night'];
const MEDIA={avatar:{max:200000},banner:{max:600000},ingame:{max:1000000}};
const MIME={'image/webp':[[0x52,0x49,0x46,0x46]],'image/jpeg':[[0xff,0xd8,0xff]],'image/png':[[0x89,0x50,0x4e,0x47]]};
function decodeImage(dataUrl,kind){const m=typeof dataUrl==='string'&&dataUrl.match(/^data:(image\/(?:webp|jpeg|png));base64,([A-Za-z0-9+/=]+)$/);if(!m)fail('Imagem inválida. Usa PNG, JPG ou WEBP.');const bytes=Buffer.from(m[2],'base64');if(!bytes.length||bytes.length>MEDIA[kind].max)fail('Imagem demasiado grande.',413);if(!MIME[m[1]].some(sig=>sig.every((b,i)=>bytes[i]===b)))fail('Imagem inválida. Usa PNG, JPG ou WEBP.');return {mime:m[1],data:m[2]}}
export function avatarUrl(u){if(!u)return null;if(u.avatar_kind==='upload'&&u.media_version>0)return `/api/media/${u.id}/avatar?v=${u.media_version}`;if(u.avatar_kind==='discord'&&u.discord_avatar&&u.discord_id)return `https://cdn.discordapp.com/avatars/${u.discord_id}/${u.discord_avatar}.${String(u.discord_avatar).startsWith('a_')?'gif':'png'}?size=256`;return null}
export function bannerOf(u){if(!u)return {preset:'lime'};if(u.banner_kind==='upload'&&u.media_version>0)return {url:`/api/media/${u.id}/banner?v=${u.media_version}`};if(u.banner_kind==='discord'&&u.discord_banner&&u.discord_id)return {url:`https://cdn.discordapp.com/banners/${u.discord_id}/${u.discord_banner}.${String(u.discord_banner).startsWith('a_')?'gif':'png'}?size=1024`};return {preset:BANNERS.includes(u.banner_preset)?u.banner_preset:'lime'}}
function ticketUrl(env){if(env.DISCORD_TICKET_URL&&/^https:\/\/(discord\.com|discord\.gg|ptb\.discord\.com)\//.test(env.DISCORD_TICKET_URL))return env.DISCORD_TICKET_URL;if(/^\d{16,22}$/.test(env.DISCORD_GUILD_ID||''))return 'https://discord.com/channels/'+env.DISCORD_GUILD_ID+(/^\d{16,22}$/.test(env.DISCORD_TICKET_CHANNEL_ID||'')?'/'+env.DISCORD_TICKET_CHANNEL_ID:'');return null}
const signedIn=actor=>{if(!actor.admin&&!actor.user.discord_id)fail('Entra com Discord para completar o perfil.',403)};
const flagCode=v=>{const s=typeof v==='string'?v.trim().toUpperCase():'';if(!FLAG_CODE.test(s))fail('Escolhe um país válido.');return s};
function nextNickChange(u){const last=Date.parse(u?.nick_changed_at||'')||0;return last?new Date(last+NICK_COOLDOWN).toISOString():null}
function nextIdChange(u){const last=Math.max(Date.parse(u?.mamo_set_at||'')||0,Date.parse(u?.mamo_request_at||'')||0);return last?new Date(last+ID_COOLDOWN).toISOString():null}
function nextFlagChange(u){const last=Math.max(Date.parse(u?.flag_set_at||'')||0,Date.parse(u?.flag_request_at||'')||0);return last?new Date(last+FLAG_COOLDOWN).toISOString():null}
function waitText(ms){const t=Math.ceil(ms/60000),h=Math.floor(t/60),m=t%60;return h?`${h}h ${m}min`:`${m}min`}
const sha=async(s)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const json=(obj,status=200)=>Response.json(obj,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
function admin(actor){if(!actor.admin)fail('Esta ação exige permissão de administração.',403)}
function member(actor){if(!actor.admin&&!actor.verifiedMember)fail(actor.user.discord_id?'É necessário confirmar que pertences ao servidor da liga.':'Entra com Discord para continuar.',403)}
async function limit(db,key,max=60){const t=Math.floor(Date.now()/1000),window=Math.floor(t/60);const r=await db.prepare('INSERT INTO rates (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key+':'+window,t+120).first();if(r.count>max)fail('Demasiados pedidos. Tenta novamente dentro de um minuto.',429);await run(db,'DELETE FROM rates WHERE expires < ?',t)}
export function localMode(req,env){return env.NODE_ENV==='development'&&!env.VERCEL&&env.NEXUS_LOCAL_ADMIN==='true'&&['localhost','127.0.0.1'].includes(new URL(req.url).hostname)}
async function userForSite(req,env){
 const session=await discordSession(req,env);if(session)return {...session,platformOwner:false};
 if(localMode(req,env)){await run(env.DB,"INSERT OR IGNORE INTO users (id,nick,mamo,owner,created) VALUES ('local-admin','Local admin','',0,?)",now());const user=await one(env.DB,"SELECT * FROM users WHERE id='local-admin'");return {user,admin:true,verifiedMember:true,platformOwner:false,authMethod:'local',source:'website'}}
 fail('Inicia sessão com Discord para continuar.',401);
}
async function userForBot(req,env,body){if(!env.BOT_API_SECRET||!env.DISCORD_GUILD_ID)fail('Bot ainda não configurado.',503);const token=req.headers.get('Authorization')?.replace(/^Bearer /,'')||'';if((await sha(token))!==(await sha(env.BOT_API_SECRET)))fail('Credencial do bot inválida.',401);const actor=body.actor;if(!actor||actor.guildId!==env.DISCORD_GUILD_ID||!/^\d{16,22}$/.test(actor.id||''))fail('Servidor ou membro inválido.',403);await limit(env.DB,'bot:'+actor.id,45);let user=await one(env.DB,'SELECT * FROM users WHERE discord_id=?',actor.id);if(!user){await run(env.DB,"INSERT OR IGNORE INTO users (id,discord_id,discord_name,nick,mamo,owner,onboarding_status,created) VALUES (?,?,?,?,?,0,'required',?)",crypto.randomUUID(),actor.id,clean(actor.username,80),'','',now());user=await one(env.DB,'SELECT * FROM users WHERE discord_id=?',actor.id)}const isAdmin=Boolean(user.owner)||(env.DISCORD_ADMIN_ROLE_IDS||'').split(',').filter(Boolean).some(id=>(actor.roles||[]).includes(id.trim()));return {user,admin:isAdmin,verifiedMember:true,authMethod:'bot',source:'discord'};}
async function audit(db,actor,text){await run(db,'INSERT INTO audit (actor,text,created) VALUES (?,?,?)',actor.user.id,text,now())}
async function snapshot(db,actor,env){const [teams,players,comps,entries,matches,awards,requests,events]=await Promise.all([
 all(db,"SELECT t.id,t.name,t.tag,t.color,t.region,t.owner_id,t.created,t.secondary_color,u.nick AS captain,CASE WHEN t.logo_mime IS NOT NULL THEN '/api/team-media/'||t.id ELSE NULL END AS logo_url,(SELECT count(DISTINCT pt.player_id) FROM player_teams pt WHERE pt.team_id=t.id AND pt.competition_id IS NOT NULL) AS members FROM teams t JOIN users u ON u.id=t.owner_id ORDER BY t.id"),all(db,'SELECT * FROM players ORDER BY id'),all(db,'SELECT * FROM competitions ORDER BY id'),all(db,'SELECT * FROM entries ORDER BY id'),all(db,'SELECT * FROM matches ORDER BY competition_id,stage,round,slot'),all(db,'SELECT * FROM awards ORDER BY created DESC'),all(db,actor.admin?'SELECT r.*,u.nick FROM requests r JOIN users u ON u.id=r.user_id ORDER BY r.id DESC':'SELECT r.*,u.nick FROM requests r JOIN users u ON u.id=r.user_id WHERE r.user_id=? ORDER BY r.id DESC',...(actor.admin?[]:[actor.user.id||''])),actor.admin?all(db,'SELECT text,created FROM audit ORDER BY id DESC LIMIT 30'):Promise.resolve([])]);
 const me=actor.user.id?await one(db,'SELECT * FROM users WHERE id=?',actor.user.id):null;
 const flagRequests=actor.admin?await all(db,"SELECT r.*,u.nick,u.discord_name FROM flag_requests r JOIN users u ON u.id=r.user_id WHERE r.status='Pendente' ORDER BY r.id"):me?await all(db,'SELECT * FROM flag_requests WHERE user_id=? ORDER BY id DESC LIMIT 5',me.id):[];
 const onboardingRequests=actor.admin?await all(db,"SELECT id,nick,discord_name,mamo,ingame_flag,onboarding_status,media_version FROM users WHERE onboarding_status IN ('required','pending','rejected') ORDER BY created DESC"):[];
 const [teamRosters,teamInvites,idRequests,linkedUsers]=await Promise.all([all(db,"SELECT pt.*,p.nick,p.mamo,p.position,t.name AS team_name,c.name AS competition_name FROM player_teams pt JOIN players p ON p.id=pt.player_id JOIN teams t ON t.id=pt.team_id LEFT JOIN competitions c ON c.id=pt.competition_id ORDER BY pt.id"),actor.admin?all(db,"SELECT i.*,p.nick,p.mamo,t.name AS team_name,c.name AS competition_name,u.nick AS manager FROM team_invites i JOIN players p ON p.id=i.player_id JOIN teams t ON t.id=i.team_id LEFT JOIN competitions c ON c.id=i.competition_id JOIN users u ON u.id=t.owner_id ORDER BY i.id DESC"):all(db,"SELECT i.*,p.nick,p.mamo,t.name AS team_name,c.name AS competition_name,u.nick AS manager FROM team_invites i JOIN players p ON p.id=i.player_id JOIN teams t ON t.id=i.team_id LEFT JOIN competitions c ON c.id=i.competition_id JOIN users u ON u.id=t.owner_id WHERE t.owner_id=? OR i.player_id=? ORDER BY i.id DESC",actor.user.id||'',actor.user.player_id||0),actor.admin?all(db,"SELECT r.*,u.nick,u.discord_name FROM id_requests r JOIN users u ON u.id=r.user_id WHERE r.status='Pendente' ORDER BY r.id"):me?all(db,'SELECT * FROM id_requests WHERE user_id=? ORDER BY id DESC LIMIT 5',me.id):Promise.resolve([]),all(db,'SELECT id,player_id,discord_id,discord_avatar,avatar_kind,media_version FROM users WHERE player_id IS NOT NULL')]);
 const avatarByPlayer=Object.fromEntries(linkedUsers.map(u=>[u.player_id,avatarUrl(u)]));
 return {teams,teamRosters,teamInvites,players:players.map(p=>({...p,team:p.team_id,teams:teamRosters.filter(r=>r.player_id===p.id).map(r=>({id:r.team_id,name:r.team_name,competition:r.competition_name})),goals:0,assists:0,avatar:avatarByPlayer[p.id]||null})),competitions:comps.map(c=>({...c,minPlayers:c.min_players??5,maxPlayers:c.max_players??10,teams:c.capacity,rawStatus:c.status,status:({open:'Inscrições abertas',active:'Em curso',finished:'Concluída',generating:'A preparar'})[c.status],color:FORMAT_COLORS[c.format]||'',subtitle:c.season})),entries,matches,awards,requests:requests.map(r=>({...r,user:r.user_id,player:r.player_id})),events:events.map(e=>({...e,time:new Date(e.created).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})})),profile:{id:actor.user.id,nick:actor.user.nick,mamo:actor.user.mamo,flag:me?.ingame_flag||'',discord:actor.user.discord_name,discordId:actor.user.discord_id,player:actor.user.player_id,onboardingStatus:me?.onboarding_status||'complete',nickChangedAt:me?.nick_changed_at||null,nextNickChange:me?nextNickChange(me):null,mamoSetAt:me?.mamo_set_at||null,nextIdChange:me?nextIdChange(me):null,flagSetAt:me?.flag_set_at||null,nextFlagChange:me?nextFlagChange(me):null,idRequests:actor.admin?[]:idRequests,flagRequests:actor.admin?[]:flagRequests,ingameScreenshot:me?.id?'/api/media/'+me.id+'/ingame?v='+(me.media_version||0):null,avatar:avatarUrl(me),banner:bannerOf(me),style:{avatar:me?.avatar_kind||'discord',banner:me?.banner_kind||'preset',preset:me?.banner_preset||'lime'},hasDiscordAvatar:Boolean(me?.discord_avatar),hasDiscordBanner:Boolean(me?.discord_banner),uploads:me?.media_version||0},idRequests:actor.admin?idRequests:[],flagRequests:actor.admin?flagRequests:[],onboardingRequests:actor.admin?onboardingRequests:[],banners:BANNERS,permissions:{admin:actor.admin,owner:Boolean(actor.user.owner),member:actor.admin||Boolean(actor.verifiedMember),authenticated:actor.admin||actor.authMethod==='discord'||actor.source==='discord',platformOwner:Boolean(actor.platformOwner)},auth:{method:actor.authMethod||'guest',expires:actor.sessionExpires||null},config:{storageReady:Boolean(env.DB),oauth:oauthStatus(env),discordReady:Boolean(env.DISCORD_GUILD_ID&&env.BOT_API_SECRET),membershipReady:Boolean(env.DISCORD_BOT_TOKEN),guildId:env.DISCORD_GUILD_ID||null,ticketUrl:ticketUrl(env)},tables:Object.fromEntries(comps.map(c=>{const es=entries.filter(e=>e.competition_id===c.id),ms=matches.filter(m=>m.competition_id===c.id);let table=standings(es.map(e=>e.team_id),c.format==='groups + knockouts'?ms.filter(m=>m.stage==='groups'):ms);if(c.format==='undefined')table.sort((a,b)=>b.points-a.points||b.buchholz-a.buchholz||b.gd-a.gd||b.gf-a.gf||a.id-b.id);return [c.id,table]}))};
}
async function ownedTeam(db,actor,id){const t=await one(db,'SELECT * FROM teams WHERE id=?',num(id));if(!t)fail('Equipa não encontrada.',404);if(!actor.admin&&t.owner_id!==actor.user.id)fail('Só o capitão ou a administração pode gerir esta equipa.',403);return t}
async function operation(env,actor,op,data={}){const db=env.DB;const id=actor.user.id;
 if(op==='state')return snapshot(db,actor,env);
 if(!actor.admin&&['required','rejected'].includes(actor.user.onboarding_status)&&op!=='onboarding.submit')fail('Completa primeiro a configuração do teu perfil.',403);
 if(!actor.admin&&actor.user.onboarding_status==='pending'&&op!=='state')fail('O teu perfil está a aguardar confirmação da administração.',403);
 if(op==='onboarding.submit'){if(!actor?.user?.id)fail('A tua sessão expirou. Entra novamente com Discord.',401);const nick=clean(data.nick,24),mamo=mamoId(data.mamo),flag=flagCode(data.flag),img=data.screenshot?decodeImage(data.screenshot,'ingame'):null;const u=await one(db,'SELECT * FROM users WHERE id=?',id);if(!u)fail('Conta não encontrada.',404);if(!['required','rejected'].includes(u.onboarding_status))fail('O teu perfil já foi enviado ou confirmado.',409);if(await one(db,"SELECT id FROM users WHERE lower(mamo)=lower(?) AND id<>?",mamo,id))fail('Esse ID Mamoball já pertence a outra conta.',409);const t=now();const onboardingQueries=[];if(img)onboardingQueries.push(db.prepare('INSERT INTO user_media (user_id,kind,mime,data,updated) VALUES (?,?,?,?,?) ON CONFLICT(user_id,kind) DO UPDATE SET mime=excluded.mime,data=excluded.data,updated=excluded.updated').bind(id,'ingame',img.mime,img.data,t));onboardingQueries.push(db.prepare('UPDATE users SET nick=?,nick_changed_at=?,mamo=?,mamo_set_at=?,ingame_flag=?,flag_set_at=?,onboarding_status=\'pending\' WHERE id=?').bind(nick,t,mamo,t,flag,t,id));await db.batch(onboardingQueries);await audit(db,actor,'Primeiro perfil enviado para confirmação: '+nick+' · '+mamo+' · '+flag);return {message:'Perfil enviado. Aguarda a confirmação da administração.'}}


 if(op==='profile.update'){signedIn(actor);const nick=clean(data.nick,24),u=await one(db,'SELECT * FROM users WHERE id=?',id),next=nextNickChange(u),wait=next?Date.parse(next)-Date.now():0;if(wait>0)fail('Podes alterar o nick novamente dentro de '+waitText(wait)+'.',429);await run(db,'UPDATE users SET nick=?,nick_changed_at=? WHERE id=?',nick,now(),id);await audit(db,actor,'Perfil atualizado: '+nick);return {message:'Perfil guardado. Podes alterar o nick novamente daqui a 48 horas.'}}
 if(op==='mamo.set'){signedIn(actor);const u=await one(db,'SELECT * FROM users WHERE id=?',id);if(u.mamo)fail('O teu ID Mamoball já está definido. Para o alterares, faz um pedido.',409);const mamo=mamoId(data.mamo);if(await one(db,"SELECT id FROM users WHERE lower(mamo)=lower(?) AND id<>?",mamo,id))fail('Esse ID Mamoball já pertence a outra conta. Abre um ticket no Discord.',409);const r=await run(db,"UPDATE users SET mamo=?,mamo_set_at=? WHERE id=? AND mamo=''",mamo,now(),id);if(!r.meta.changes)fail('O teu ID Mamoball já está definido.',409);await audit(db,actor,'ID Mamoball definido: '+mamo);return {message:'ID Mamoball guardado.'}}
 if(op==='mamo.request'){signedIn(actor);const u=await one(db,'SELECT * FROM users WHERE id=?',id);if(!u.mamo)fail('Define primeiro o teu ID Mamoball.');if(await one(db,"SELECT id FROM id_requests WHERE user_id=? AND status='Pendente'",id))fail('Já tens um pedido de alteração pendente.',409);const next=nextIdChange(u),wait=next?Date.parse(next)-Date.now():0;if(wait>0)fail('Podes pedir uma nova alteração dentro de '+waitText(wait)+'.',429);const mamo=mamoId(data.mamo);if(mamo.toLowerCase()===u.mamo.toLowerCase())fail('Esse já é o teu ID Mamoball.');if(await one(db,"SELECT id FROM users WHERE lower(mamo)=lower(?) AND id<>?",mamo,id))fail('Esse ID Mamoball já pertence a outra conta. Abre um ticket no Discord.',409);const t=now();await db.batch([db.prepare("INSERT INTO id_requests (user_id,old_mamo,new_mamo,status,created) VALUES (?,?,?,'Pendente',?)").bind(id,u.mamo,mamo,t),db.prepare('UPDATE users SET mamo_request_at=? WHERE id=?').bind(t,id)]);await audit(db,actor,'Pedido de alteração de ID: '+u.mamo+' → '+mamo);return {message:'Pedido enviado à administração.'}}
 if(op==='mamo.review'){admin(actor);const r=await one(db,"SELECT * FROM id_requests WHERE id=? AND status='Pendente'",num(data.id));if(!r)fail('Pedido já tratado ou inexistente.');const status=pick(data.status,['Aprovado','Recusado']);const q=[];if(status==='Aprovado'){if(await one(db,"SELECT id FROM users WHERE lower(mamo)=lower(?) AND id<>?",r.new_mamo,r.user_id))fail('Esse ID Mamoball já pertence a outra conta.',409);const u=await one(db,'SELECT * FROM users WHERE id=?',r.user_id);q.push(db.prepare("UPDATE users SET mamo=? WHERE id=? AND EXISTS (SELECT 1 FROM id_requests WHERE id=? AND status='Pendente')").bind(r.new_mamo,r.user_id,r.id));if(u?.player_id&&!await one(db,'SELECT id FROM players WHERE lower(mamo)=lower(?) AND id<>?',r.new_mamo,u.player_id))q.push(db.prepare('UPDATE players SET mamo=? WHERE id=?').bind(r.new_mamo,u.player_id))}q.push(db.prepare("UPDATE id_requests SET status=?,reviewed_by=?,reviewed_at=? WHERE id=? AND status='Pendente'").bind(status,id,now(),r.id));const done=await db.batch(q);if(!done.at(-1).meta.changes)fail('Pedido já tratado.',409);await audit(db,actor,'Pedido de ID '+r.id+': '+status+' ('+r.old_mamo+' → '+r.new_mamo+')');return {message:'Pedido '+status.toLowerCase()+'.'}}
 if(op==='flag.request'){signedIn(actor);const u=await one(db,'SELECT * FROM users WHERE id=?',id);const requestedFlag=flagCode(data.flag);if(!u.ingame_flag){await run(db,'UPDATE users SET ingame_flag=?,flag_set_at=? WHERE id=?',requestedFlag,now(),id);await audit(db,actor,'Bandeira definida: '+requestedFlag);return {message:'Bandeira guardada.'}}if(await one(db,"SELECT id FROM flag_requests WHERE user_id=? AND status='Pendente'",id))fail('Já tens um pedido de bandeira pendente.',409);const next=nextFlagChange(u),wait=next?Date.parse(next)-Date.now():0;if(wait>0)fail('Podes pedir uma nova bandeira dentro de '+waitText(wait)+'.',429);if(requestedFlag===u.ingame_flag)fail('Essa já é a tua bandeira.');const t=now();await db.batch([db.prepare("INSERT INTO flag_requests (user_id,old_flag,new_flag,status,created) VALUES (?,?,?,'Pendente',?)").bind(id,u.ingame_flag,requestedFlag,t),db.prepare('UPDATE users SET flag_request_at=? WHERE id=?').bind(t,id)]);await audit(db,actor,'Pedido de bandeira: '+u.ingame_flag+' → '+requestedFlag);return {message:'Pedido de bandeira enviado à administração.'}}
 if(op==='flag.review'){admin(actor);const r=await one(db,"SELECT * FROM flag_requests WHERE id=? AND status='Pendente'",num(data.id));if(!r)fail('Pedido já tratado ou inexistente.');const status=pick(data.status,['Aprovado','Recusado']);const q=[];if(status==='Aprovado')q.push(db.prepare("UPDATE users SET ingame_flag=? WHERE id=? AND EXISTS (SELECT 1 FROM flag_requests WHERE id=? AND status='Pendente')").bind(r.new_flag,r.user_id,r.id));q.push(db.prepare("UPDATE flag_requests SET status=?,reviewed_by=?,reviewed_at=? WHERE id=? AND status='Pendente'").bind(status,id,now(),r.id));const done=await db.batch(q);if(!done.at(-1).meta.changes)fail('Pedido já tratado.',409);await audit(db,actor,'Pedido de bandeira '+r.id+': '+status);return {message:'Pedido de bandeira '+status.toLowerCase()+'.'}}
 if(op==='onboarding.review'){admin(actor);const target=await one(db,"SELECT * FROM users WHERE id=?",String(data.id));if(!target||target.onboarding_status!=='pending')fail('Pedido de perfil já tratado ou inexistente.');const status=pick(data.status,['Aprovado','Recusado']);const t=now();const queries=[db.prepare("UPDATE users SET onboarding_status=?,onboarding_reviewed_by=?,onboarding_reviewed_at=? WHERE id=? AND onboarding_status='pending'").bind(status==='Aprovado'?'complete':'rejected',id,t,target.id)];if(status==='Aprovado'){let player=target.player_id?await one(db,'SELECT id FROM players WHERE id=?',target.player_id):null;if(!player){player=await one(db,'SELECT id FROM players WHERE lower(mamo)=lower(?)',target.mamo);if(!player){const created=await run(db,'INSERT INTO players (nick,mamo,team_id,position,created) VALUES (?,?,?,?,?)',target.nick,target.mamo,null,'Avançado',t);player={id:created.meta.last_row_id}}queries.push(db.prepare('UPDATE users SET player_id=? WHERE id=?').bind(player.id,target.id));}}const done=await db.batch(queries);if(!done[0]?.meta.changes)fail('Pedido já tratado.',409);await audit(db,actor,'Primeiro perfil '+target.nick+': '+status+(status==='Aprovado'?' · jogador criado/associado':''));return {message:status==='Aprovado'?'Perfil aprovado e jogador criado.':'Perfil rejeitado.'}}
 if(op==='profile.style'){signedIn(actor);const avatar=pick(data.avatar,['discord','upload','initials']),banner=pick(data.banner,['preset','discord','upload']),preset=pick(data.preset||'lime',BANNERS);const u=await one(db,'SELECT * FROM users WHERE id=?',id);const has=k=>one(db,'SELECT 1 AS ok FROM user_media WHERE user_id=? AND kind=?',id,k);if(avatar==='upload'&&!await has('avatar'))fail('Carrega primeiro uma imagem de perfil.');if(banner==='upload'&&!await has('banner'))fail('Carrega primeiro um banner.');if(avatar==='discord'&&!u.discord_avatar)fail('A tua conta Discord não tem imagem de perfil.');if(banner==='discord'&&!u.discord_banner)fail('A tua conta Discord não tem banner.');await run(db,'UPDATE users SET avatar_kind=?,banner_kind=?,banner_preset=? WHERE id=?',avatar,banner,preset,id);return {message:'Perfil guardado.'}}
 if(op==='media.upload'){signedIn(actor);const kind=pick(data.kind,['avatar','banner','ingame']);const img=decodeImage(data.image,kind);await db.batch([db.prepare('INSERT INTO user_media (user_id,kind,mime,data,updated) VALUES (?,?,?,?,?) ON CONFLICT(user_id,kind) DO UPDATE SET mime=excluded.mime,data=excluded.data,updated=excluded.updated').bind(id,kind,img.mime,img.data,now()),db.prepare(`UPDATE users SET media_version=media_version+1${kind==='avatar'?',avatar_kind=\'upload\'':kind==='banner'?',banner_kind=\'upload\'':''} WHERE id=?`).bind(id)]);await audit(db,actor,kind==='avatar'?'Imagem de perfil atualizada.':'Banner atualizado.');return {message:kind==='avatar'?'Imagem de perfil atualizada.':'Banner atualizado.'}}
 if(op==='media.remove'){const kind=pick(data.kind,['avatar','banner','ingame']);let target=id;if(data.user&&data.user!==id){admin(actor);target=String(data.user).slice(0,64)}else signedIn(actor);await db.batch([db.prepare('DELETE FROM user_media WHERE user_id=? AND kind=?').bind(target,kind),db.prepare(`UPDATE users SET media_version=media_version+1${kind==='avatar'?',avatar_kind=CASE WHEN avatar_kind=\'upload\' THEN \'discord\' ELSE avatar_kind END':kind==='banner'?',banner_kind=CASE WHEN banner_kind=\'upload\' THEN \'preset\' ELSE banner_kind END':''} WHERE id=?`).bind(target)]);await audit(db,actor,(kind==='avatar'?'Imagem de perfil removida':'Banner removido')+(target!==id?' (moderação)':''));return {message:kind==='avatar'?'Imagem de perfil removida.':'Banner removido.'}}
 if(op==='link.create'){if(actor.source!=='website')fail('Cria o código no website.');if(actor.user.discord_id)fail('Esta conta já está ligada ao Discord.');if(!env.DISCORD_GUILD_ID||!env.BOT_API_SECRET)fail('Configura primeiro o bot Discord.',503);const code=crypto.randomUUID().replaceAll('-',''),hash=await sha(code);await db.batch([db.prepare('DELETE FROM links WHERE user_id=? OR expires<?').bind(id,Date.now()),db.prepare('INSERT INTO links (hash,user_id,expires) VALUES (?,?,?)').bind(hash,id,Date.now()+600000)]);return {code,expires:10,message:'No servidor da liga usa /ligar com este código. Expira em 10 minutos.'}}
 if(op==='link.consume'){if(actor.source!=='discord')fail('Este comando só pode ser usado no Discord.',403);const hash=await sha(clean(data.code,64));const link=await one(db,'SELECT * FROM links WHERE hash=? AND expires>?',hash,Date.now());if(!link)fail('Código inválido ou expirado.');const target=await one(db,'SELECT * FROM users WHERE id=?',link.user_id);if(target.discord_id||actor.user.site_id)fail('Uma das contas já está ligada. Contacta a organização.');if(target.player_id&&actor.user.player_id&&target.player_id!==actor.user.player_id)fail('As contas têm jogadores diferentes. Contacta a organização.');
 // One atomic claim prevents reusing the same linking code. Merging retains the Site account and its team ownership.
 const claim=await db.prepare('DELETE FROM links WHERE hash=? AND expires>? RETURNING user_id').bind(hash,Date.now()).first();if(!claim)fail('Código já utilizado.');
 const merged={nick:actor.user.nick||target.nick,mamo:actor.user.mamo||target.mamo,player:actor.user.player_id||target.player_id};
 await db.batch([db.prepare('UPDATE teams SET owner_id=? WHERE owner_id=?').bind(target.id,id),db.prepare('UPDATE requests SET user_id=? WHERE user_id=?').bind(target.id,id),db.prepare('DELETE FROM links WHERE user_id=?').bind(id),db.prepare('DELETE FROM users WHERE id=?').bind(id),db.prepare('UPDATE users SET discord_id=?,discord_name=?,nick=?,mamo=?,player_id=? WHERE id=? AND discord_id IS NULL').bind(actor.user.discord_id,actor.user.discord_name,merged.nick,merged.mamo,merged.player,target.id)]);return {message:'Discord ligado ao website. Atualiza a página.'}}
 if(op==='team.update'){member(actor);const t=await ownedTeam(db,actor,data.id);const name=clean(data.name,35),tag=clean(data.tag,3).toUpperCase(),color=clean(data.color,7),secondary=clean(data.secondaryColor||'#1b241b',7);if(!/^[A-Z]{3}$/.test(tag))fail('A abreviatura tem de conter exatamente 3 letras.');if(!/^#[a-f0-9]{6}$/i.test(color)||!/^#[a-f0-9]{6}$/i.test(secondary))fail('Cor inválida.');if(await one(db,'SELECT id FROM teams WHERE (lower(name)=lower(?) OR lower(tag)=lower(?)) AND id<>?',name,tag,t.id))fail('Nome ou abreviatura já utilizado.',409);if(data.logo){const logo=decodeImage(data.logo,'avatar');await run(db,'UPDATE teams SET name=?,tag=?,color=?,secondary_color=?,logo_mime=?,logo_data=? WHERE id=?',name,tag,color,secondary,logo.mime,logo.data,t.id)}else await run(db,'UPDATE teams SET name=?,tag=?,color=?,secondary_color=? WHERE id=?',name,tag,color,secondary,t.id);await audit(db,actor,'Equipa atualizada: '+name);return {message:'Detalhes da equipa guardados.'}}
 if(op==='team.invite'){member(actor);const t=await ownedTeam(db,actor,data.team),c=await one(db,'SELECT * FROM competitions WHERE id=?',num(data.competition)),player=await one(db,'SELECT * FROM players WHERE id=?',num(data.player));if(!c)fail('Competição não encontrada.',404);if(!player)fail('Jogador não encontrado.',404);if(!await one(db,'SELECT id FROM users WHERE player_id=?',player.id))fail('Este jogador ainda não tem uma conta MES ligada ao Discord.',409);if(!await one(db,'SELECT id FROM entries WHERE team_id=? AND competition_id=?',t.id,c.id))fail('A equipa não está inscrita nesta competição.',409);if(!['open','active'].includes(c.status))fail('Esta competição já não aceita alterações ao plantel.',409);if(player.id===actor.user.player_id)fail('Não podes convidar-te a ti próprio.');if(await one(db,'SELECT id FROM player_teams WHERE player_id=? AND competition_id=?',player.id,c.id))fail('Este jogador já pertence a uma equipa nesta competição.',409);if(await one(db,"SELECT id FROM team_invites WHERE team_id=? AND competition_id=? AND player_id=? AND status='Pendente'",t.id,c.id,player.id))fail('Já existe um convite pendente para este jogador.',409);const counts=await one(db,"SELECT (SELECT count(*) FROM player_teams WHERE team_id=? AND competition_id=?) AS active,(SELECT count(*) FROM team_invites WHERE team_id=? AND competition_id=? AND status='Pendente') AS pending",t.id,c.id,t.id,c.id);if(Number(counts.active||0)+Number(counts.pending||0)>=Number(c.max_players||10))fail('O plantel atingiu o máximo de '+(c.max_players||10)+' jogadores.',409);await run(db,"INSERT INTO team_invites (team_id,player_id,competition_id,status,created) VALUES (?,?,?,'Pendente',?)",t.id,player.id,c.id,now());await audit(db,actor,'Convite enviado a '+player.nick+' para '+t.name+' · '+c.name);return {message:'Convite enviado.'}}
 if(op==='team.invite.respond'){member(actor);const invite=await one(db,"SELECT i.*,c.status AS competition_status,c.max_players FROM team_invites i JOIN competitions c ON c.id=i.competition_id WHERE i.id=? AND i.status='Pendente'",num(data.id));if(!invite)fail('Convite inexistente ou já tratado.',404);if(!actor.admin&&(!actor.user.player_id||actor.user.player_id!==invite.player_id))fail('Este convite não pertence à tua conta de jogador.',403);const status=pick(data.status,['Aceite','Recusado']);if(status==='Aceite'){if(!['open','active'].includes(invite.competition_status))fail('Esta competição já não aceita alterações ao plantel.',409);if(await one(db,'SELECT id FROM player_teams WHERE player_id=? AND competition_id=?',invite.player_id,invite.competition_id))fail('Já pertences a uma equipa nesta competição.',409);const n=await one(db,'SELECT count(*) AS n FROM player_teams WHERE team_id=? AND competition_id=?',invite.team_id,invite.competition_id);if(Number(n?.n||0)>=Number(invite.max_players||10))fail('O plantel já atingiu o máximo de jogadores.',409);const done=await db.batch([db.prepare('INSERT INTO player_teams (player_id,team_id,competition_id,created) VALUES (?,?,?,?)').bind(invite.player_id,invite.team_id,invite.competition_id,now()),db.prepare("UPDATE team_invites SET status='Aceite',reviewed_by=?,reviewed_at=? WHERE id=? AND status='Pendente'").bind(id,now(),invite.id)]);if(!done.at(-1).meta.changes)fail('O convite já foi tratado.',409)}else await run(db,"UPDATE team_invites SET status='Recusado',reviewed_by=?,reviewed_at=? WHERE id=? AND status='Pendente'",id,now(),invite.id);await audit(db,actor,'Convite '+invite.id+': '+status);return {message:status==='Aceite'?'Convite aceite. Já pertences ao plantel desta competição.':'Convite recusado.'}}
 if(op==='team.invite.cancel'){member(actor);const t=await ownedTeam(db,actor,data.team),invite=await one(db,"SELECT * FROM team_invites WHERE id=? AND team_id=? AND status='Pendente'",num(data.id),t.id);if(!invite)fail('Convite pendente não encontrado.',404);await run(db,"UPDATE team_invites SET status='Cancelado',reviewed_by=?,reviewed_at=? WHERE id=? AND status='Pendente'",id,now(),invite.id);return {message:'Convite cancelado.'}}
 if(op==='team.player.remove'){member(actor);const t=await ownedTeam(db,actor,data.team),competitionId=num(data.competition),playerId=num(data.player);if(!await one(db,'SELECT id FROM player_teams WHERE team_id=? AND competition_id=? AND player_id=?',t.id,competitionId,playerId))fail('Jogador não encontrado neste plantel.',404);const c=await one(db,'SELECT * FROM competitions WHERE id=?',competitionId);if(!c||!['open','active'].includes(c.status))fail('Não podes alterar o plantel nesta fase da competição.',409);await run(db,'DELETE FROM player_teams WHERE team_id=? AND competition_id=? AND player_id=?',t.id,competitionId,playerId);await audit(db,actor,'Jogador removido do plantel: '+playerId+' · '+t.name);return {message:'Jogador removido do plantel desta competição.'}}
 if(op==='team.create'){member(actor);if(!actor.user.nick)fail('Completa primeiro o teu perfil.');const name=clean(data.name,35),tag=clean(data.tag,3).toUpperCase(),color=clean(data.color,7),secondary=clean(data.secondaryColor||'#1b241b',7);if(!/^[A-Z]{3}$/.test(tag))fail('A abreviatura tem de conter exatamente 3 letras.');if(!/^#[a-f0-9]{6}$/i.test(color)||!/^#[a-f0-9]{6}$/i.test(secondary))fail('Cor inválida.');if(!data.logo)fail('Carrega o logótipo da equipa.');const logo=decodeImage(data.logo,'avatar');let competitionId=data.competition?num(data.competition):null;if(!actor.admin&&!competitionId)fail('Escolhe uma competição com inscrições abertas.');const competition=competitionId?await one(db,'SELECT * FROM competitions WHERE id=?',competitionId):null;if(competitionId&&!competition)fail('Competição não encontrada.');if(!actor.admin&&competition.status!=='open')fail('Só podes registar equipas numa competição em fase de inscrições.');if(competitionId&&competition.status!=='open'&&!actor.admin)fail('As inscrições desta competição estão fechadas.');if(competitionId&&Number((await one(db,'SELECT count(*) AS n FROM entries WHERE competition_id=?',competitionId))?.n||0)>=competition.capacity)fail('Esta competição já está completa.');if(await one(db,'SELECT id FROM teams WHERE lower(name)=lower(?) OR lower(tag)=lower(?)',name,tag))fail('Nome ou abreviatura já utilizado.');const t=now();const created=await run(db,'INSERT INTO teams (name,tag,color,region,owner_id,created,logo_mime,logo_data,secondary_color) VALUES (?,?,?,?,?,?,?,?,?)',name,tag,color,'',id,t,logo.mime,logo.data,secondary);const teamId=created.meta.last_row_id;if(actor.user.player_id&&competitionId&&await one(db,'SELECT id FROM player_teams WHERE player_id=? AND competition_id=?',actor.user.player_id,competitionId)){await run(db,'DELETE FROM teams WHERE id=?',teamId);fail('Já pertences a uma equipa nesta competição.',409)}if(actor.user.player_id){await run(db,'INSERT OR IGNORE INTO team_members (team_id,player_id,status,created) VALUES (?,?,?,?)',teamId,actor.user.player_id,'active',t);if(competitionId)await run(db,'INSERT OR IGNORE INTO player_teams (player_id,team_id,competition_id,created) VALUES (?,?,?,?)',actor.user.player_id,teamId,competitionId,t)}if(competitionId){const entry=await run(db,"INSERT INTO entries (competition_id,team_id,group_name,created) SELECT ?,?,'',? WHERE (SELECT count(*) FROM entries WHERE competition_id=?) < ? AND ((SELECT status FROM competitions WHERE id=?)='open' OR ?=1)",competitionId,teamId,t,competitionId,competition.capacity,competitionId,actor.admin?1:0);if(!entry.meta.changes){await run(db,'DELETE FROM teams WHERE id=?',teamId);fail('As inscrições fecharam ou a competição está completa.',409)}}await audit(db,actor,'Equipa criada: '+name+(competition?' · '+competition.name:''));return {message:competition?'Equipa criada e inscrita na competição.':'Equipa criada pela administração.'}}
 if(op==='player.create'){admin(actor);const nick=clean(data.nick,24),mamo=mamoId(data.mamo),teamId=Number(data.team)||null;if(teamId&&!await one(db,'SELECT id FROM teams WHERE id=?',teamId))fail('Equipa não encontrada.');if(await one(db,'SELECT id FROM players WHERE lower(nick)=lower(?) OR lower(mamo)=lower(?)',nick,mamo))fail('Nick ou ID Mamoball já registado.');await run(db,'INSERT INTO players (nick,mamo,team_id,position,created) VALUES (?,?,?,?,?)',nick,mamo,teamId,pick(data.position,['Avançado','Médio','Defesa','Guarda-redes']),now());await audit(db,actor,'Jogador registado: '+nick);return {message:'Jogador registado.'}}
 if(op==='request.create'){member(actor);if(actor.user.player_id)fail('Já tens um jogador associado.');const player=num(data.player);if(!await one(db,'SELECT id FROM players WHERE id=?',player))fail('Jogador não encontrado.');if(await one(db,"SELECT id FROM requests WHERE user_id=? AND status='Pendente'",id))fail('Já tens um pedido pendente.');if(await one(db,'SELECT id FROM users WHERE player_id=?',player))fail('Esse jogador já está associado a outra conta.');await run(db,'INSERT INTO requests (user_id,player_id,status,created) VALUES (?,?,?,?)',id,player,'Pendente',now());await audit(db,actor,'Pedido de associação submetido.');return {message:'Pedido enviado à organização.'}}
 if(op==='request.review'){admin(actor);const r=await one(db,"SELECT * FROM requests WHERE id=? AND status='Pendente'",num(data.id));if(!r)fail('Pedido já tratado ou inexistente.');const status=pick(data.status,['Aprovado','Recusado']);const queries=[];if(status==='Aprovado'){if(await one(db,'SELECT id FROM users WHERE player_id=?',r.player_id))fail('Jogador já associado.');const u=await one(db,'SELECT * FROM users WHERE id=?',r.user_id);if(u.player_id)fail('A conta já tem um jogador.');queries.push(db.prepare("UPDATE users SET player_id=? WHERE id=? AND player_id IS NULL AND EXISTS (SELECT 1 FROM requests WHERE id=? AND status='Pendente')").bind(r.player_id,r.user_id,r.id))}queries.push(db.prepare("UPDATE requests SET status=? WHERE id=? AND status='Pendente'").bind(status,r.id));const reviewed=await db.batch(queries);if(!reviewed.at(-1).meta.changes)fail('Pedido já tratado.',409);await audit(db,actor,'Pedido '+r.id+': '+status);return {message:'Pedido '+status.toLowerCase()+'.'}}
 if(op==='competition.create'){admin(actor);const name=clean(data.name,45),format=pick(data.format,FORMATS),mode=pick(data.mode,['1v1','2v2','3v3','4v4','5v5','6v6','7v7']),season=typeof data.season==='string'?data.season.trim().slice(0,30):'',capacity=Number(data.teams),minPlayers=Number(data.minPlayers??5),maxPlayers=Number(data.maxPlayers??10);if(!Number.isSafeInteger(minPlayers)||!Number.isSafeInteger(maxPlayers)||minPlayers<1||maxPlayers<minPlayers||maxPlayers>50)fail('Define um mínimo e máximo de jogadores válidos (1–50).');if(!Number.isSafeInteger(capacity)||capacity<2)fail('Capacidade inválida.');if(format==='groups + knockouts'&&!([8,16,32,64].includes(capacity)))fail('Grupos + knockouts usa 8, 16, 32 ou 64 lugares.');if(format!=='groups + knockouts'&&capacity<2)fail('Capacidade inválida.');if(await one(db,'SELECT id FROM competitions WHERE lower(name)=lower(?)',name))fail('Nome já utilizado.');await run(db,'INSERT INTO competitions (name,format,mode,capacity,season,status,round,rounds,version,created,min_players,max_players) VALUES (?,?,?,?,?,?,0,0,0,?,?,?)',name,format,mode,capacity,season,'open',now(),minPlayers,maxPlayers);await audit(db,actor,'Competição criada: '+name);return {message:'Competição criada.'}}
 if(op==='entry.create'){if(!actor.admin)fail('Esta ação exige permissão de administração.',403);const t=await ownedTeam(db,actor,data.team),c=await one(db,'SELECT * FROM competitions WHERE id=?',num(data.competition));if(!c||c.status!=='open')fail('As inscrições não estão abertas.');if(await one(db,'SELECT id FROM entries WHERE competition_id=? AND team_id=?',c.id,t.id))fail('Equipa já inscrita.');const result=await run(db,"INSERT INTO entries (competition_id,team_id,group_name,created) SELECT ?,?,'',? WHERE (SELECT count(*) FROM entries WHERE competition_id=?) < ? AND (SELECT status FROM competitions WHERE id=?)='open'",c.id,t.id,now(),c.id,c.capacity,c.id);if(!result.meta.changes)fail('As inscrições fecharam ou a competição está completa.');await audit(db,actor,'Inscrição: '+t.name+' em '+c.name);return {message:'Inscrição confirmada.'}}
 if(op==='competition.start'||op==='competition.advance'){admin(actor);const c=await one(db,'SELECT * FROM competitions WHERE id=?',num(data.id));if(!c)fail('Competição não encontrada.');if(op==='competition.start'&&c.status!=='open')fail('Esta competição já começou.');if(op==='competition.start'){const rosterEntries=await all(db,'SELECT team_id FROM entries WHERE competition_id=?',c.id);for(const e of rosterEntries){const n=await one(db,'SELECT count(*) AS n FROM player_teams WHERE competition_id=? AND team_id=?',c.id,e.team_id);if(Number(n?.n||0)<Number(c.min_players||1))fail('Cada equipa precisa de pelo menos '+c.min_players+' jogadores aceites antes de iniciar a competição.');}}if(op==='competition.advance'&&c.status!=='active')fail('A competição não está ativa.');const lock=await db.prepare('UPDATE competitions SET status=?,version=version+1 WHERE id=? AND status=? AND version=? RETURNING id').bind('generating',c.id,c.status,c.version).first();if(!lock)fail('A competição foi alterada. Atualiza e tenta novamente.',409);
 let fixtures=[];try{const es=await all(db,'SELECT * FROM entries WHERE competition_id=? ORDER BY id',c.id),ms=await all(db,'SELECT * FROM matches WHERE competition_id=? ORDER BY stage,round,slot',c.id),ids=es.map(e=>e.team_id);fixtures=op==='competition.start'?initialFixtures(c.format,ids):nextFixtures(c,es,ms);if(!fixtures.length)fail('Não há mais rondas. Podes encerrar a competição.');const queries=[];if(c.format==='groups + knockouts'&&op==='competition.start')es.forEach((e,i)=>queries.push(db.prepare('UPDATE entries SET group_name=? WHERE id=?').bind(String.fromCharCode(65+Math.floor(i/4)),e.id)));fixtures.forEach((m,i)=>queries.push(db.prepare('INSERT INTO matches (competition_id,stage,round,slot,group_name,home_id,away_id,version) VALUES (?,?,?,?,?,?,?,0)').bind(c.id,m.stage,m.round,i,m.group,m.home,m.away)));const total=c.format==='undefined'?Math.ceil(Math.log2(ids.length)):Math.max(...fixtures.map(m=>m.round));queries.push(db.prepare('UPDATE competitions SET status=?,round=?,rounds=? WHERE id=?').bind('active',Math.max(...fixtures.map(m=>m.round)),op==='competition.start'?total:c.rounds,c.id));await db.batch(queries)}catch(e){await run(db,'UPDATE competitions SET status=? WHERE id=? AND status=?',c.status,c.id,'generating');throw e}await audit(db,actor,'Jogos gerados: '+c.name);return {message:fixtures.length+' jogos gerados.'}}
 if(op==='match.update'){admin(actor);const m=await one(db,'SELECT m.*,c.status,c.version AS competition_version FROM matches m JOIN competitions c ON c.id=m.competition_id WHERE m.id=?',num(data.id));if(!m||m.status!=='active')fail('Jogo não disponível para edição.');const scheduled=data.scheduled?new Date(data.scheduled).toISOString():null;const hs=data.homeScore===''||data.homeScore===null?null:Number(data.homeScore),as=data.awayScore===''||data.awayScore===null?null:Number(data.awayScore);if((hs===null)!==(as===null)||[hs,as].some(s=>s!==null&&(!Number.isInteger(s)||s<0||s>99)))fail('Indica ambos os resultados, entre 0 e 99.');let winner=hs===null?null:hs>as?m.home_id:as>hs?m.away_id:null;if(m.stage==='knockout'&&hs!==null&&hs===as){winner=Number(data.winner)||null;if(![m.home_id,m.away_id].includes(winner))fail('Indica o vencedor do desempate.')}if(await one(db,"SELECT id FROM matches WHERE competition_id=? AND ((stage='knockout' AND ?='groups') OR (stage=? AND round>? AND ? IN ('swiss','knockout'))) LIMIT 1",m.competition_id,m.stage,m.stage,m.round,m.stage)){// Only dependent stages freeze previous results; league fixtures are independent.
 const c=await one(db,'SELECT format FROM competitions WHERE id=?',m.competition_id);if(c.format!=='league'&&(hs!==m.home_score||as!==m.away_score||winner!==m.winner_id))fail('Os resultados desta fase estão bloqueados porque a fase seguinte já foi gerada.')}
 const lock=await db.prepare("UPDATE competitions SET status='generating',version=version+1 WHERE id=? AND status='active' AND version=? RETURNING id").bind(m.competition_id,m.competition_version).first();if(!lock)fail('A competição foi alterada. Atualiza antes de guardar.',409);try{const result=await run(db,'UPDATE matches SET home_score=?,away_score=?,winner_id=?,scheduled=?,version=version+1 WHERE id=? AND version=?',hs,as,winner,scheduled,m.id,Number(data.version));if(!result.meta.changes)fail('O jogo foi alterado. Atualiza antes de guardar.',409);}finally{await run(db,"UPDATE competitions SET status='active' WHERE id=? AND status='generating'",m.competition_id)}await audit(db,actor,'Jogo #'+m.id+' atualizado.');return {message:'Jogo atualizado.'}}
 if(op==='competition.finish'){admin(actor);const c=await one(db,'SELECT * FROM competitions WHERE id=?',num(data.id));if(!c||c.status!=='active')fail('Competição não está ativa.');const lock=await db.prepare("UPDATE competitions SET status='generating',version=version+1 WHERE id=? AND status='active' AND version=? RETURNING id").bind(c.id,c.version).first();if(!lock)fail('A competição foi alterada. Tenta novamente.',409);try{const es=await all(db,'SELECT * FROM entries WHERE competition_id=?',c.id),ms=await all(db,'SELECT * FROM matches WHERE competition_id=?',c.id),win=champion(c,es,ms);if(!win)fail('Conclui todos os jogos e fases antes de encerrar.');await db.batch([db.prepare("UPDATE competitions SET status='finished' WHERE id=? AND status='generating'").bind(c.id),db.prepare('INSERT INTO awards (competition_id,type,team_id,created) VALUES (?,?,?,?)').bind(c.id,'Campeão',win,now())]);}catch(e){await run(db,"UPDATE competitions SET status='active' WHERE id=? AND status='generating'",c.id);throw e}await audit(db,actor,'Época concluída: '+c.name);return {message:'Competição encerrada. Campeão adicionado ao Hall of Fame.'}}
 if(op==='award.create'){admin(actor);const c=await one(db,"SELECT * FROM competitions WHERE id=? AND status='finished'",num(data.competition));if(!c)fail('Encerra a competição antes de atribuir prémios.');const player=await one(db,'SELECT * FROM players WHERE id=?',num(data.player));if(!player)fail('Jogador não encontrado.');if(!player.team_id||!await one(db,'SELECT id FROM entries WHERE competition_id=? AND team_id=?',c.id,player.team_id))fail('O jogador tem de pertencer a uma equipa inscrita nesta competição.');await run(db,'INSERT INTO awards (competition_id,type,player_id,created) VALUES (?,?,?,?)',c.id,pick(data.type,['MVP','Bota de ouro']),player.id,now());return {message:'Prémio adicionado ao Hall of Fame.'}}
 if(op==='export'){admin(actor);return snapshot(db,actor,env)}
 fail('Operação desconhecida.',404);
}
export async function handle(req,env){try{if(!env.DB){if(req.method==='GET'&&new URL(req.url).pathname==='/api/state')return json(await previewState(env));fail('A liga está em preparação. A base de dados ainda não foi configurada.',503);}const url=new URL(req.url);const authResponse=await authRoutes(req,env);if(authResponse)return authResponse;if(req.method==='GET'&&url.pathname==='/api/health'){await one(env.DB,'SELECT count(*) AS n FROM settings');return json({ok:true,version:'2.0',storage:'libSQL',discordConfigured:Boolean(env.DISCORD_GUILD_ID&&env.BOT_API_SECRET)})}const teamMedia=url.pathname.match(/^\/api\/team-media\/(\d+)$/);if(teamMedia&&req.method==='GET'){const row=await one(env.DB,'SELECT logo_mime,logo_data FROM teams WHERE id=?',Number(teamMedia[1]));if(!row?.logo_mime||!row?.logo_data)return new Response('Not found',{status:404,headers:{'Cache-Control':'no-store'}});return new Response(Buffer.from(row.logo_data,'base64'),{headers:{'Content-Type':row.logo_mime,'Cache-Control':'public, max-age=300','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; img-src 'self'; style-src 'unsafe-inline'",'Content-Disposition':'inline'}})}const media=url.pathname.match(/^\/api\/media\/([\w-]{1,64})\/(avatar|banner|ingame)$/);if(media&&req.method==='GET'){const row=await one(env.DB,'SELECT mime,data FROM user_media WHERE user_id=? AND kind=?',media[1],media[2]);if(!row)return new Response('Not found',{status:404,headers:{'Cache-Control':'no-store'}});return new Response(Buffer.from(row.data,'base64'),{headers:{'Content-Type':row.mime,'Cache-Control':'public, max-age=31536000, immutable','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; img-src 'self'; style-src 'unsafe-inline'",'Content-Disposition':'inline'}})}
 const isBot=url.pathname==='/api/bot';if(!['GET','POST'].includes(req.method))fail('Método não permitido.',405);if(req.method==='POST'&&!isBot){const origin=req.headers.get('Origin');if(origin!==url.origin)fail('Origem inválida.',403);if(req.headers.get('X-Nexus-Request')!=='1')fail('Pedido inválido.',403)}let body={};if(req.method==='POST'){if(!req.headers.get('Content-Type')?.includes('application/json'))fail('Usa JSON.',415);const raw=await req.text();if(raw.length>1500000)fail('Pedido demasiado grande.',413);try{body=JSON.parse(raw)}catch{fail('JSON inválido.')}if(raw.length>16384&&!['media.upload','onboarding.submit'].includes(body?.op))fail('Pedido demasiado grande.',413);}const guest=req.method==='GET'&&url.pathname==='/api/state'&&!localMode(req,env)&&!req.headers.get('Cookie')?.includes('nexus_session=');const actor=guest?{user:{id:null,nick:'',mamo:'',discord_name:null,discord_id:null,player_id:null,owner:0},admin:false,verifiedMember:false,source:'guest',authMethod:'guest'}:isBot?await userForBot(req,env,body):await userForSite(req,env);if(!isBot&&req.method==='POST')await limit(env.DB,'web:'+actor.user.id);if(req.method==='GET'&&url.pathname==='/api/state')return json(await snapshot(env.DB,actor,env));if(req.method!=='POST')fail('Rota não encontrada.',404);if(!isBot&&url.pathname!=='/api/action')fail('Rota não encontrada.',404);const result=await operation(env,actor,body.op,body.data||{});return json(result)}catch(error){if(error instanceof AuthError){const messages={session_expired:'A sessão Discord expirou. Entra novamente.',not_member:'Já não pertences ao servidor da liga.',membership_pending:'Conclui a verificação de entrada no servidor Discord.',discord_unavailable:'O Discord está temporariamente indisponível. Tenta novamente.',not_configured:'O login Discord ainda precisa de configuração.'};return json({error:messages[error.code]||'Não foi possível validar a sessão Discord.',authError:error.code},error.status)}if(error instanceof AppError)return json({error:error.message},error.status);const msg=String(error?.message||'');if(/UNIQUE constraint|unique constraint/i.test(msg))return json({error:'Este registo já existe ou já foi associado. Atualiza a página.'},409);if(/São necessárias|formato|emparelhar|resultados|vencedor|equipas|eliminar|grupos/i.test(msg)&&!msg.includes('SQL'))return json({error:msg},400);console.error('Nexus request failed',error?.name);return json({error:'N��o foi possível concluir a operação. Tenta novamente.'},500)}}

async function previewState(env){
 const empty={prepare(){return {bind(){return this},async all(){return {results:[]}}}}};
 const actor={user:{id:null,nick:'',mamo:'',discord_name:null,discord_id:null,player_id:null,owner:0},admin:false,verifiedMember:false,source:'guest',authMethod:'guest'};
 const result=await snapshot(empty,actor,env);result.config.oauth.ready=false;return result;
}
