import { authRoutes, discordSession, oauthStatus, AuthError } from './oauth.mjs';
import { FORMATS,initialFixtures,nextFixtures,standings,champion } from './engine.mjs';
const now=()=>new Date().toISOString();
class AppError extends Error{constructor(message,status=400){super(message);this.status=status}}
const fail=(s,status=400)=>{throw new AppError(s,status)};
const clean=(v,max=80)=>{if(typeof v!=='string'||!v.trim()||v.trim().length>max)fail('Campo obrigatório inválido.');return v.trim()};
const num=v=>{const n=Number(v);if(!Number.isSafeInteger(n)||n<1)fail('Identificador inválido.');return n};
const pick=(v,values)=>values.includes(v)?v:fail('Opção inválida.');
const all=async(db,sql,...args)=>(await db.prepare(sql).bind(...args).all()).results;
const one=async(db,sql,...args)=>db.prepare(sql).bind(...args).first();
const run=async(db,sql,...args)=>db.prepare(sql).bind(...args).run();
const sha=async(s)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const json=(obj,status=200)=>Response.json(obj,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
function admin(actor){if(!actor.admin)fail('Esta ação exige permissão de administração.',403)}
function member(actor){if(!actor.admin&&!actor.verifiedMember)fail(actor.user.discord_id?'É necessário confirmar que pertences ao servidor da liga.':'Entra com Discord para continuar.',403)}
async function limit(db,key,max=60){const t=Math.floor(Date.now()/1000),window=Math.floor(t/60);const r=await db.prepare('INSERT INTO rates (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key+':'+window,t+120).first();if(r.count>max)fail('Demasiados pedidos. Tenta novamente dentro de um minuto.',429);await run(db,'DELETE FROM rates WHERE expires < ?',t)}
export function localMode(req,env){return env.NODE_ENV==='development'&&!env.VERCEL&&env.NEXUS_LOCAL_ADMIN==='true'&&['localhost','127.0.0.1'].includes(new URL(req.url).hostname)}
async function userForSite(req,env){
 const session=await discordSession(req,env);if(session)return {...session,platformOwner:false};
 if(localMode(req,env)){await run(env.DB,"INSERT OR IGNORE INTO users (id,nick,mamo,owner,created) VALUES ('local-admin','Local admin','',0,?)",now());const user=await one(env.DB,"SELECT * FROM users WHERE id='local-admin'");return {user,admin:true,verifiedMember:true,platformOwner:false,authMethod:'local',source:'website'}}
 fail('Inicia sessão com Discord para continuar.',401);
}
async function userForBot(req,env,body){if(!env.BOT_API_SECRET||!env.DISCORD_GUILD_ID)fail('Bot ainda não configurado.',503);const token=req.headers.get('Authorization')?.replace(/^Bearer /,'')||'';if((await sha(token))!==(await sha(env.BOT_API_SECRET)))fail('Credencial do bot inválida.',401);const actor=body.actor;if(!actor||actor.guildId!==env.DISCORD_GUILD_ID||!/^\d{16,22}$/.test(actor.id||''))fail('Servidor ou membro inválido.',403);await limit(env.DB,'bot:'+actor.id,45);let user=await one(env.DB,'SELECT * FROM users WHERE discord_id=?',actor.id);if(!user){await run(env.DB,'INSERT OR IGNORE INTO users (id,discord_id,discord_name,nick,mamo,owner,created) VALUES (?,?,?,?,?,0,?)',crypto.randomUUID(),actor.id,clean(actor.username,80),'','',now());user=await one(env.DB,'SELECT * FROM users WHERE discord_id=?',actor.id)}const isAdmin=Boolean(user.owner)||(env.DISCORD_ADMIN_ROLE_IDS||'').split(',').filter(Boolean).some(id=>(actor.roles||[]).includes(id.trim()));return {user,admin:isAdmin,verifiedMember:true,authMethod:'bot',source:'discord'};}
async function audit(db,actor,text){await run(db,'INSERT INTO audit (actor,text,created) VALUES (?,?,?)',actor.user.id,text,now())}
async function snapshot(db,actor,env){const [teams,players,comps,entries,matches,awards,requests,events]=await Promise.all([
 all(db,'SELECT t.*,u.nick AS captain,(SELECT count(*) FROM players WHERE team_id=t.id) AS members FROM teams t JOIN users u ON u.id=t.owner_id ORDER BY t.id'),all(db,'SELECT * FROM players ORDER BY id'),all(db,'SELECT * FROM competitions ORDER BY id'),all(db,'SELECT * FROM entries ORDER BY id'),all(db,'SELECT * FROM matches ORDER BY competition_id,stage,round,slot'),all(db,'SELECT * FROM awards ORDER BY created DESC'),all(db,actor.admin?'SELECT r.*,u.nick FROM requests r JOIN users u ON u.id=r.user_id ORDER BY r.id DESC':'SELECT r.*,u.nick FROM requests r JOIN users u ON u.id=r.user_id WHERE r.user_id=? ORDER BY r.id DESC',...(actor.admin?[]:[actor.user.id||''])),actor.admin?all(db,'SELECT text,created FROM audit ORDER BY id DESC LIMIT 30'):Promise.resolve([])]);
 return {teams,players:players.map(p=>({...p,team:p.team_id,goals:0,assists:0})),competitions:comps.map(c=>({...c,teams:c.capacity,rawStatus:c.status,status:({open:'Inscrições abertas',active:'Em curso',finished:'Concluída',generating:'A preparar'})[c.status],color:({Liga:'','Eliminação direta':'purple','Grupos + playoffs':'orange','Sistema suíço':'blue'})[c.format],subtitle:c.season})),entries,matches,awards,requests:requests.map(r=>({...r,user:r.user_id,player:r.player_id})),events:events.map(e=>({...e,time:new Date(e.created).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})})),profile:{id:actor.user.id,nick:actor.user.nick,mamo:actor.user.mamo,discord:actor.user.discord_name,discordId:actor.user.discord_id,player:actor.user.player_id},permissions:{admin:actor.admin,owner:Boolean(actor.user.owner),member:actor.admin||Boolean(actor.verifiedMember),authenticated:actor.admin||actor.authMethod==='discord'||actor.source==='discord',platformOwner:Boolean(actor.platformOwner)},auth:{method:actor.authMethod||'guest',expires:actor.sessionExpires||null},config:{oauth:oauthStatus(env),discordReady:Boolean(env.DISCORD_GUILD_ID&&env.BOT_API_SECRET),membershipReady:Boolean(env.DISCORD_BOT_TOKEN),guildId:env.DISCORD_GUILD_ID||null},tables:Object.fromEntries(comps.map(c=>{const es=entries.filter(e=>e.competition_id===c.id),ms=matches.filter(m=>m.competition_id===c.id);let table=standings(es.map(e=>e.team_id),c.format==='Grupos + playoffs'?ms.filter(m=>m.stage==='groups'):ms);if(c.format==='Sistema suíço')table.sort((a,b)=>b.points-a.points||b.buchholz-a.buchholz||b.gd-a.gd||b.gf-a.gf||a.id-b.id);return [c.id,table]}))};
}
async function ownedTeam(db,actor,id){const t=await one(db,'SELECT * FROM teams WHERE id=?',num(id));if(!t)fail('Equipa não encontrada.',404);if(!actor.admin&&t.owner_id!==actor.user.id)fail('Só o capitão ou a administração pode gerir esta equipa.',403);return t}
async function operation(env,actor,op,data={}){const db=env.DB;const id=actor.user.id;
 if(op==='state')return snapshot(db,actor,env);


 if(op==='profile.update'){if(!actor.admin&&!actor.user.discord_id)fail('Entra com Discord para completar o perfil.',403);const nick=clean(data.nick,24),mamo=clean(data.mamo,40);await run(db,'UPDATE users SET nick=?,mamo=? WHERE id=?',nick,mamo,id);await audit(db,actor,'Perfil atualizado: '+nick);return {message:'Perfil guardado.'}}
 if(op==='link.create'){if(actor.source!=='website')fail('Cria o código no website.');if(actor.user.discord_id)fail('Esta conta já está ligada ao Discord.');if(!env.DISCORD_GUILD_ID||!env.BOT_API_SECRET)fail('Configura primeiro o bot Discord.',503);const code=crypto.randomUUID().replaceAll('-',''),hash=await sha(code);await db.batch([db.prepare('DELETE FROM links WHERE user_id=? OR expires<?').bind(id,Date.now()),db.prepare('INSERT INTO links (hash,user_id,expires) VALUES (?,?,?)').bind(hash,id,Date.now()+600000)]);return {code,expires:10,message:'No servidor da liga usa /ligar com este código. Expira em 10 minutos.'}}
 if(op==='link.consume'){if(actor.source!=='discord')fail('Este comando só pode ser usado no Discord.',403);const hash=await sha(clean(data.code,64));const link=await one(db,'SELECT * FROM links WHERE hash=? AND expires>?',hash,Date.now());if(!link)fail('Código inválido ou expirado.');const target=await one(db,'SELECT * FROM users WHERE id=?',link.user_id);if(target.discord_id||actor.user.site_id)fail('Uma das contas já está ligada. Contacta a organização.');if(target.player_id&&actor.user.player_id&&target.player_id!==actor.user.player_id)fail('As contas têm jogadores diferentes. Contacta a organização.');
 // One atomic claim prevents reusing the same linking code. Merging retains the Site account and its team ownership.
 const claim=await db.prepare('DELETE FROM links WHERE hash=? AND expires>? RETURNING user_id').bind(hash,Date.now()).first();if(!claim)fail('Código já utilizado.');
 const merged={nick:actor.user.nick||target.nick,mamo:actor.user.mamo||target.mamo,player:actor.user.player_id||target.player_id};
 await db.batch([db.prepare('UPDATE teams SET owner_id=? WHERE owner_id=?').bind(target.id,id),db.prepare('UPDATE requests SET user_id=? WHERE user_id=?').bind(target.id,id),db.prepare('DELETE FROM links WHERE user_id=?').bind(id),db.prepare('DELETE FROM users WHERE id=?').bind(id),db.prepare('UPDATE users SET discord_id=?,discord_name=?,nick=?,mamo=?,player_id=? WHERE id=? AND discord_id IS NULL').bind(actor.user.discord_id,actor.user.discord_name,merged.nick,merged.mamo,merged.player,target.id)]);return {message:'Discord ligado ao website. Atualiza a página.'}}
 if(op==='team.create'){member(actor);if(!actor.user.nick)fail('Completa primeiro o teu perfil.');const name=clean(data.name,35),tag=clean(data.tag,3).toUpperCase(),color=clean(data.color,7);if(!/^#[a-f0-9]{6}$/i.test(color))fail('Cor inválida.');if(await one(db,'SELECT id FROM teams WHERE lower(name)=lower(?) OR lower(tag)=lower(?)',name,tag))fail('Nome ou abreviatura já utilizado.');await run(db,'INSERT INTO teams (name,tag,color,region,owner_id,created) VALUES (?,?,?,?,?,?)',name,tag,color,pick(data.region,['Portugal','Brasil','Internacional']),id,now());await audit(db,actor,'Equipa criada: '+name);return {message:'Equipa registada.'}}
 if(op==='player.create'){admin(actor);const nick=clean(data.nick,24),mamo=clean(data.mamo,40),teamId=Number(data.team)||null;if(teamId&&!await one(db,'SELECT id FROM teams WHERE id=?',teamId))fail('Equipa não encontrada.');if(await one(db,'SELECT id FROM players WHERE lower(nick)=lower(?) OR lower(mamo)=lower(?)',nick,mamo))fail('Nick ou ID Mamoball já registado.');await run(db,'INSERT INTO players (nick,mamo,team_id,position,created) VALUES (?,?,?,?,?)',nick,mamo,teamId,pick(data.position,['Avançado','Médio','Defesa','Guarda-redes']),now());await audit(db,actor,'Jogador registado: '+nick);return {message:'Jogador registado.'}}
 if(op==='request.create'){member(actor);if(actor.user.player_id)fail('Já tens um jogador associado.');const player=num(data.player);if(!await one(db,'SELECT id FROM players WHERE id=?',player))fail('Jogador não encontrado.');if(await one(db,"SELECT id FROM requests WHERE user_id=? AND status='Pendente'",id))fail('Já tens um pedido pendente.');if(await one(db,'SELECT id FROM users WHERE player_id=?',player))fail('Esse jogador já está associado a outra conta.');await run(db,'INSERT INTO requests (user_id,player_id,status,created) VALUES (?,?,?,?)',id,player,'Pendente',now());await audit(db,actor,'Pedido de associação submetido.');return {message:'Pedido enviado à organização.'}}
 if(op==='request.review'){admin(actor);const r=await one(db,"SELECT * FROM requests WHERE id=? AND status='Pendente'",num(data.id));if(!r)fail('Pedido já tratado ou inexistente.');const status=pick(data.status,['Aprovado','Recusado']);const queries=[];if(status==='Aprovado'){if(await one(db,'SELECT id FROM users WHERE player_id=?',r.player_id))fail('Jogador já associado.');const u=await one(db,'SELECT * FROM users WHERE id=?',r.user_id);if(u.player_id)fail('A conta já tem um jogador.');queries.push(db.prepare("UPDATE users SET player_id=? WHERE id=? AND player_id IS NULL AND EXISTS (SELECT 1 FROM requests WHERE id=? AND status='Pendente')").bind(r.player_id,r.user_id,r.id))}queries.push(db.prepare("UPDATE requests SET status=? WHERE id=? AND status='Pendente'").bind(status,r.id));const reviewed=await db.batch(queries);if(!reviewed.at(-1).meta.changes)fail('Pedido já tratado.',409);await audit(db,actor,'Pedido '+r.id+': '+status);return {message:'Pedido '+status.toLowerCase()+'.'}}
 if(op==='competition.create'){admin(actor);const name=clean(data.name,45),format=pick(data.format,FORMATS),mode=pick(data.mode,['1v1','2v2','3v3','4v4']),capacity=Number(data.teams);if(![4,8,16,32].includes(capacity))fail('Capacidade inválida.');if(format==='Grupos + playoffs'&&capacity<8)fail('Grupos + playoffs exige pelo menos 8 lugares.');if(await one(db,'SELECT id FROM competitions WHERE lower(name)=lower(?)',name))fail('Nome já utilizado.');await run(db,'INSERT INTO competitions (name,format,mode,capacity,season,status,round,rounds,version,created) VALUES (?,?,?,?,?,?,0,0,0,?)',name,format,mode,capacity,clean(data.season||'Época 01',40),'open',now());await audit(db,actor,'Competição criada: '+name);return {message:'Competição criada.'}}
 if(op==='entry.create'){member(actor);const t=await ownedTeam(db,actor,data.team),c=await one(db,'SELECT * FROM competitions WHERE id=?',num(data.competition));if(!c||c.status!=='open')fail('As inscrições não estão abertas.');if(await one(db,'SELECT id FROM entries WHERE competition_id=? AND team_id=?',c.id,t.id))fail('Equipa já inscrita.');const result=await run(db,"INSERT INTO entries (competition_id,team_id,group_name,created) SELECT ?,?,'',? WHERE (SELECT count(*) FROM entries WHERE competition_id=?) < ? AND (SELECT status FROM competitions WHERE id=?)='open'",c.id,t.id,now(),c.id,c.capacity,c.id);if(!result.meta.changes)fail('As inscrições fecharam ou a competição está completa.');await audit(db,actor,'Inscrição: '+t.name+' em '+c.name);return {message:'Inscrição confirmada.'}}
 if(op==='competition.start'||op==='competition.advance'){admin(actor);const c=await one(db,'SELECT * FROM competitions WHERE id=?',num(data.id));if(!c)fail('Competição não encontrada.');if(op==='competition.start'&&c.status!=='open')fail('Esta competição já começou.');if(op==='competition.advance'&&c.status!=='active')fail('A competição não está ativa.');const lock=await db.prepare('UPDATE competitions SET status=?,version=version+1 WHERE id=? AND status=? AND version=? RETURNING id').bind('generating',c.id,c.status,c.version).first();if(!lock)fail('A competição foi alterada. Atualiza e tenta novamente.',409);
 let fixtures=[];try{const es=await all(db,'SELECT * FROM entries WHERE competition_id=? ORDER BY id',c.id),ms=await all(db,'SELECT * FROM matches WHERE competition_id=? ORDER BY stage,round,slot',c.id),ids=es.map(e=>e.team_id);fixtures=op==='competition.start'?initialFixtures(c.format,ids):nextFixtures(c,es,ms);if(!fixtures.length)fail('Não há mais rondas. Podes encerrar a competição.');const queries=[];if(c.format==='Grupos + playoffs'&&op==='competition.start')es.forEach((e,i)=>queries.push(db.prepare('UPDATE entries SET group_name=? WHERE id=?').bind(String.fromCharCode(65+Math.floor(i/4)),e.id)));fixtures.forEach((m,i)=>queries.push(db.prepare('INSERT INTO matches (competition_id,stage,round,slot,group_name,home_id,away_id,version) VALUES (?,?,?,?,?,?,?,0)').bind(c.id,m.stage,m.round,i,m.group,m.home,m.away)));const total=c.format==='Sistema suíço'?Math.ceil(Math.log2(ids.length)):Math.max(...fixtures.map(m=>m.round));queries.push(db.prepare('UPDATE competitions SET status=?,round=?,rounds=? WHERE id=?').bind('active',Math.max(...fixtures.map(m=>m.round)),op==='competition.start'?total:c.rounds,c.id));await db.batch(queries)}catch(e){await run(db,'UPDATE competitions SET status=? WHERE id=? AND status=?',c.status,c.id,'generating');throw e}await audit(db,actor,'Jogos gerados: '+c.name);return {message:fixtures.length+' jogos gerados.'}}
 if(op==='match.update'){admin(actor);const m=await one(db,'SELECT m.*,c.status,c.version AS competition_version FROM matches m JOIN competitions c ON c.id=m.competition_id WHERE m.id=?',num(data.id));if(!m||m.status!=='active')fail('Jogo não disponível para edição.');const scheduled=data.scheduled?new Date(data.scheduled).toISOString():null;const hs=data.homeScore===''||data.homeScore===null?null:Number(data.homeScore),as=data.awayScore===''||data.awayScore===null?null:Number(data.awayScore);if((hs===null)!==(as===null)||[hs,as].some(s=>s!==null&&(!Number.isInteger(s)||s<0||s>99)))fail('Indica ambos os resultados, entre 0 e 99.');let winner=hs===null?null:hs>as?m.home_id:as>hs?m.away_id:null;if(m.stage==='knockout'&&hs!==null&&hs===as){winner=Number(data.winner)||null;if(![m.home_id,m.away_id].includes(winner))fail('Indica o vencedor do desempate.')}if(await one(db,"SELECT id FROM matches WHERE competition_id=? AND ((stage='knockout' AND ?='groups') OR (stage=? AND round>? AND ? IN ('swiss','knockout'))) LIMIT 1",m.competition_id,m.stage,m.stage,m.round,m.stage)){// Only dependent stages freeze previous results; league fixtures are independent.
 const c=await one(db,'SELECT format FROM competitions WHERE id=?',m.competition_id);if(c.format!=='Liga'&&(hs!==m.home_score||as!==m.away_score||winner!==m.winner_id))fail('Os resultados desta fase estão bloqueados porque a fase seguinte já foi gerada.')}
 const lock=await db.prepare("UPDATE competitions SET status='generating',version=version+1 WHERE id=? AND status='active' AND version=? RETURNING id").bind(m.competition_id,m.competition_version).first();if(!lock)fail('A competição foi alterada. Atualiza antes de guardar.',409);try{const result=await run(db,'UPDATE matches SET home_score=?,away_score=?,winner_id=?,scheduled=?,version=version+1 WHERE id=? AND version=?',hs,as,winner,scheduled,m.id,Number(data.version));if(!result.meta.changes)fail('O jogo foi alterado. Atualiza antes de guardar.',409);}finally{await run(db,"UPDATE competitions SET status='active' WHERE id=? AND status='generating'",m.competition_id)}await audit(db,actor,'Jogo #'+m.id+' atualizado.');return {message:'Jogo atualizado.'}}
 if(op==='competition.finish'){admin(actor);const c=await one(db,'SELECT * FROM competitions WHERE id=?',num(data.id));if(!c||c.status!=='active')fail('Competição não está ativa.');const lock=await db.prepare("UPDATE competitions SET status='generating',version=version+1 WHERE id=? AND status='active' AND version=? RETURNING id").bind(c.id,c.version).first();if(!lock)fail('A competição foi alterada. Tenta novamente.',409);try{const es=await all(db,'SELECT * FROM entries WHERE competition_id=?',c.id),ms=await all(db,'SELECT * FROM matches WHERE competition_id=?',c.id),win=champion(c,es,ms);if(!win)fail('Conclui todos os jogos e fases antes de encerrar.');await db.batch([db.prepare("UPDATE competitions SET status='finished' WHERE id=? AND status='generating'").bind(c.id),db.prepare('INSERT INTO awards (competition_id,type,team_id,created) VALUES (?,?,?,?)').bind(c.id,'Campeão',win,now())]);}catch(e){await run(db,"UPDATE competitions SET status='active' WHERE id=? AND status='generating'",c.id);throw e}await audit(db,actor,'Época concluída: '+c.name);return {message:'Competição encerrada. Campeão adicionado ao Hall of Fame.'}}
 if(op==='award.create'){admin(actor);const c=await one(db,"SELECT * FROM competitions WHERE id=? AND status='finished'",num(data.competition));if(!c)fail('Encerra a competição antes de atribuir prémios.');const player=await one(db,'SELECT * FROM players WHERE id=?',num(data.player));if(!player)fail('Jogador não encontrado.');if(!player.team_id||!await one(db,'SELECT id FROM entries WHERE competition_id=? AND team_id=?',c.id,player.team_id))fail('O jogador tem de pertencer a uma equipa inscrita nesta competição.');await run(db,'INSERT INTO awards (competition_id,type,player_id,created) VALUES (?,?,?,?)',c.id,pick(data.type,['MVP','Bota de ouro']),player.id,now());return {message:'Prémio adicionado ao Hall of Fame.'}}
 if(op==='export'){admin(actor);return snapshot(db,actor,env)}
 fail('Operação desconhecida.',404);
}
export async function handle(req,env){try{if(!env.DB)fail('Base de dados indisponível.',503);const url=new URL(req.url);const authResponse=await authRoutes(req,env);if(authResponse)return authResponse;if(req.method==='GET'&&url.pathname==='/api/health'){await one(env.DB,'SELECT count(*) AS n FROM settings');return json({ok:true,version:'2.0',storage:'libSQL',discordConfigured:Boolean(env.DISCORD_GUILD_ID&&env.BOT_API_SECRET)})}const isBot=url.pathname==='/api/bot';if(!['GET','POST'].includes(req.method))fail('Método não permitido.',405);if(req.method==='POST'&&!isBot){const origin=req.headers.get('Origin');if(origin!==url.origin)fail('Origem inválida.',403);if(req.headers.get('X-Nexus-Request')!=='1')fail('Pedido inválido.',403)}let body={};if(req.method==='POST'){if(!req.headers.get('Content-Type')?.includes('application/json'))fail('Usa JSON.',415);const raw=await req.text();if(raw.length>16384)fail('Pedido demasiado grande.',413);try{body=JSON.parse(raw)}catch{fail('JSON inválido.')}}const guest=req.method==='GET'&&url.pathname==='/api/state'&&!localMode(req,env)&&!req.headers.get('Cookie')?.includes('nexus_session=');const actor=guest?{user:{id:null,nick:'',mamo:'',discord_name:null,discord_id:null,player_id:null,owner:0},admin:false,verifiedMember:false,source:'guest',authMethod:'guest'}:isBot?await userForBot(req,env,body):await userForSite(req,env);if(!isBot&&req.method==='POST')await limit(env.DB,'web:'+actor.user.id);if(req.method==='GET'&&url.pathname==='/api/state')return json(await snapshot(env.DB,actor,env));if(req.method!=='POST')fail('Rota não encontrada.',404);if(!isBot&&url.pathname!=='/api/action')fail('Rota não encontrada.',404);const result=await operation(env,actor,body.op,body.data||{});return json(result)}catch(error){if(error instanceof AuthError){const messages={session_expired:'A sessão Discord expirou. Entra novamente.',not_member:'Já não pertences ao servidor da liga.',membership_pending:'Conclui a verificação de entrada no servidor Discord.',discord_unavailable:'O Discord está temporariamente indisponível. Tenta novamente.',not_configured:'O login Discord ainda precisa de configuração.'};return json({error:messages[error.code]||'Não foi possível validar a sessão Discord.',authError:error.code},error.status)}if(error instanceof AppError)return json({error:error.message},error.status);const msg=String(error?.message||'');if(/UNIQUE constraint|unique constraint/i.test(msg))return json({error:'Este registo já existe ou já foi associado. Atualiza a página.'},409);if(/São necessárias|formato|emparelhar|resultados|vencedor|equipas|eliminar|grupos/i.test(msg)&&!msg.includes('SQL'))return json({error:msg},400);console.error('Nexus request failed',error?.name);return json({error:'Não foi possível concluir a operação. Tenta novamente.'},500)}}
